# Generated by Django 4.1.3 on 2022-12-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_delete_commentimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dislike',
            options={'verbose_name': 'Не нравится', 'verbose_name_plural': 'Не нравится'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Нравится', 'verbose_name_plural': 'Нравится'},
        ),
    ]
